Homework6
anetagloc/pp_workshop pull request #12
Opened 2024-08-05 14:16 UTC by anetagloc

Adding controller tests and styles for login and registration

2024-08-05 19:23 UTC, IsoldeFair requested changes
bomba!!! jedynie popraw proszę wcięcia i dodaj jeden test na redirect :)

2024-08-05 19:23 UTC, IsoldeFair commented on spec/controllers/articles_controller_spec.rb
> +  subject(:index) { get :index }
tu to wcięcie powinno zostać jak w linijce wyżej :)

2024-08-05 19:23 UTC, IsoldeFair commented on spec/controllers/articles_controller_spec.rb
> +        it { is_expected.to_not be_successful}
proszę dodaj jeszcze test na redirect :)

2024-08-05 19:23 UTC, IsoldeFair commented on spec/controllers/articles_controller_spec.rb
> +  subject(:show) { get :show, params: { id: article.id } }
tu również pogubiły się wcięcia :)

2024-08-06 10:16 UTC, brisitech commented
Poprawione :)

2024-08-06 15:08 UTC, merged