Homework2
anetagloc/pp_workshop pull request #2
Opened 2024-06-10 16:10 UTC by anetagloc

2024-06-11 17:06 UTC, IsoldeFair requested changes
wszystko niiiby działa jak należy, tzn da się dodać i usunąć obrazek, ale widoki są nieco poprzesuwane i w przypadku błędu walidacji niestety pojawia się czerwone okienko ale nie ma tekstu ;)
dodatkowo, dodałam Ci komentarze gdzie zmienić kod w widokach ponieważ bez tego "persisted" wywala się błąd jak na screenie, bo railsy próbują pokazać że jakiś plik był dodany, ale on w rzeczywistości się nie dodał bo był błąd walidacji pola, w moim przypadku pola body
<img width="1047" alt="Screenshot 2024-06-11 at 18 39 18" src="https://github.com/anetagloc/pp_workshop/assets/64915231/7f0b2ff0-4403-4f64-ba4f-fa568cb68397">

<img width="1360" alt="Screenshot 2024-06-11 at 18 56 48" src="https://github.com/anetagloc/pp_workshop/assets/64915231/e35d0511-70f9-4bf5-8a9d-d0ed2361e5d8">

2024-06-11 17:06 UTC, IsoldeFair commented on app/views/articles/_article.html.erb
> +  <td class="px-3 py-3 "><% if article.image.attached? %>
```suggestion
  <td class="px-3 py-3 "><% if article.image.attached? && article.image.persisted? %>
```

2024-06-11 17:06 UTC, IsoldeFair commented on app/views/articles/edit.html.erb
> +    <% if @article.image.attached? %>
```suggestion
    <% if @article.image.attached? && @article.image.persisted? %>
```

2024-06-13 19:38 UTC, anetagloc commented on app/views/articles/edit.html.erb
> +    <% if @article.image.attached? %>
Musi być article bez małpy bo inaczej pojawia się błąd

2024-06-13 19:38 UTC, anetagloc commented on app/views/articles/_article.html.erb
> +  <td class="px-3 py-3 "><% if article.image.attached? %>
Musi być article bez małpy bo inaczej pojawia się błąd

2024-06-13 19:39 UTC, anetagloc commented on app/views/articles/edit.html.erb
> +    <% if @article.image.attached? %>
Poprawione

2024-06-14 11:16 UTC, closed without merging